-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 21:07:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SemImagesDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SemImagesDatabase` ;

-- -----------------------------------------------------
-- Schema SemImagesDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SemImagesDatabase` DEFAULT CHARACTER SET utf8 ;
USE `SemImagesDatabase` ;

-- -----------------------------------------------------
-- Table `SemImagesDatabase`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SemImagesDatabase`.`images` ;

CREATE TABLE IF NOT EXISTS `SemImagesDatabase`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image` LONGBLOB NOT NULL,
  `beam_kv` INT NULL,
  `magnification` INT NULL,
  `working_depth` INT NULL,
  UNIQUE INDEX `image_id_UNIQUE` (`image_id` ASC),
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
