-- MySQL Script generated by MySQL Workbench
-- Sat Mar  3 19:52:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FusorDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FusorDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FusorDB` DEFAULT CHARACTER SET utf8 ;
USE `FusorDB` ;

-- -----------------------------------------------------
-- Table `FusorDB`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`pictures` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`pictures` (
  `picture_id` INT NOT NULL AUTO_INCREMENT,
  `picture` BLOB NULL,
  PRIMARY KEY (`picture_id`),
  UNIQUE INDEX `picture_id_UNIQUE` (`picture_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FusorDB`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`favorites` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`favorites` (
  `favorite_id` INT UNSIGNED NOT NULL,
  `favorite` BLOB NULL,
  PRIMARY KEY (`favorite_id`),
  UNIQUE INDEX `Picture_id_UNIQUE` (`favorite_id` ASC),
  CONSTRAINT `Picture_id`
    FOREIGN KEY (`favorite_id`)
    REFERENCES `FusorDB`.`pictures` (`picture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FusorDB`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`session` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`session` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `time` TEXT NULL,
  `date` TEXT NULL,
  PRIMARY KEY (`session_id`),
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FusorDB`.`operators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`operators` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`operators` (
  `operator_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` TEXT NULL,
  `last_name` TEXT NULL,
  `initials` TEXT NULL,
  PRIMARY KEY (`operator_id`),
  UNIQUE INDEX `operator_id_UNIQUE` (`operator_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FusorDB`.`session_ops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`session_ops` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`session_ops` (
  `session_id` INT NOT NULL,
  `operator_id` INT NOT NULL,
  PRIMARY KEY (`session_id`, `operator_id`),
  INDEX `operator_id_idx` (`operator_id` ASC),
  CONSTRAINT `session_id`
    FOREIGN KEY (`session_id`)
    REFERENCES `FusorDB`.`session` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `operator_id`
    FOREIGN KEY (`operator_id`)
    REFERENCES `FusorDB`.`operators` (`operator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
