-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 22:15:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FusorDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FusorDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FusorDB` DEFAULT CHARACTER SET utf8 ;
USE `FusorDB` ;

-- -----------------------------------------------------
-- Table `FusorDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`Users` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `Name` TEXT NULL,
  `time_in` TEXT NULL,
  `time_out` TEXT NULL,
  `time_on` TEXT NULL,
  `time_off` TEXT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_id_UNIQUE` (`User_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FusorDB`.`Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`Pictures` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`Pictures` (
  `Picture_id` INT NOT NULL,
  `Picture` BLOB NULL,
  PRIMARY KEY (`Picture_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FusorDB`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FusorDB`.`favorites` ;

CREATE TABLE IF NOT EXISTS `FusorDB`.`favorites` (
  `Picture_id` INT NOT NULL,
  `Picture` BLOB NULL,
  PRIMARY KEY (`Picture_id`),
  CONSTRAINT `Picture_id`
    FOREIGN KEY (`Picture_id`)
    REFERENCES `FusorDB`.`Pictures` (`Picture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
